title: ENJOY EVERY MOMENT
author: ASHWINI MOHAN
email: ashwini@quintype.com
description: > Enjoy every moment of your life. Life is short. :heart:

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
